service: gitlab
type: Add gitlab member
image: awrmin/add_gitlab_members
fields:
    - key: privateToken
      type: text
    - key: id
      type: text
    - key: userId
      type: text
    - key: accessLevel
      type: text
    - key: expiresAt
      type: text
    - key: source
      type: text
author: Armingodiz
icon: https://cdn-icons-png.flaticon.com/512/5968/5968853.png
description: Adds a member with given userId to gitlab project or group(source must be "project" or "group")
