service: dotenx
type: Write file
image: awrmin/write-file:lambda
fields:
    - key: name
      type: text
      description: name of your person 
    - key: age
      type: text
      description: age of your person 
outputs:
    - key: file
      type: text
      description: name of your created file 
author: Armingodiz
icon: https://cdn4.vectorstock.com/i/1000x1000/81/83/document-file-logo-vector-25068183.jpg
node_color: A04000
description: write file with given inputs

