service: stripe
type: Stripe create payment link
image: dotenx/task-and-trigger:stripe-create-payment-link-lambda4
integrations: [stripe]
fields:
    - key: CUS_ID
      type: text
      description: customer's Stripe id (e.g cus_asdfg8234sad)
      display_name: customer id
    - key: SUCCESS_URL
      type: text
      description: address of your website that your users should be redirect to it when payment is successfull (e.g https://example.web.dotenx.com/payment/success)
      display_name: success url
    - key: CANCEL_URL
      type: text
      description: address of your website that your users should be redirect to it when payment is not successfull (e.g https://example.web.dotenx.com/payment/cancel)
      display_name: cancel url
    - key: SHOPPING_BAG
      type: object
      description: "a json format field that keys are price IDs and values are quantities (e.g { \"price_esl4sdcx5\": 2})"
      display_name: shopping bag
outputs:
    - key: payment_url
      type: text
      description: payment url
      display_name: payment url
author: Hojjat-1
icon: https://upload.wikimedia.org/wikipedia/commons/b/ba/Stripe_Logo%2C_revised_2016.svg
node_color: 665BFF
description: create payment link for checkout basket in Stripe
