service: stripe
type: Stripe find customer
image: hawwwdi/stripe-find-customer:latest
integrations: [stripe]
fields:
    - key: CUS_EMAIL
      type: text
      description: customer's email address (e.g abc@gmail.com)
    - key: CUS_ID
      type: text
      description: customer's stripe Id (e.g cus_sadfa8234sad)
author: hawwwdi
icon: https://seeklogo.com/images/S/stripe-logo-C409DC9652-seeklogo.com.png
node_color: FBFB11
description: Finds an existing customer by their email address or Stripe ID.
