service: openai
type: Create Blog Post
image: dotenx/task-and-trigger:open-ai-create-blog-post-lambda2
integrations: [openai]
fields:
    - key: explanation
      type: text
      display_name: "Explanation"
      description: "Explanations about subject of blog post or a summary of contents that should be written."
    - key: keywords
      type: text
      display_name: "* Keywords"
      description: "Some keywords that blog post is about them. Keywords can be separated by ',', '-' or something else."
    - key: output_format
      type: text
      display_name: "Output Format"
      description: "Format of blog post content, e.g: 'markdown', 'html', 'txt'"
author: Hojjat-1
icon: https://seeklogo.com/images/O/open-ai-logo-8B9BFEDC26-seeklogo.com.png
node_color: A3A3A3
description: "Creates a blog post with Open AI (using your api key) and retrieve it in desired format"
